### Description
- Added one more layer to the network and increased the hidden nodes. 
- I have implemented the neural network in such a way that it'll give us all the outputs using all the activation functions. 
- Firslty I have defined all the required activation functions like sigmoid, relu and tanh. 
- Secondly defined the model(forward and backward propagation) with all the activation functions, so that we can compare the results, which is best of all, which is overfitting, underfitting or the perfect fit.

In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
def sigmoid(z):
    return (1.0/(1.0 + np.exp(-z)))

def sigmoid_deravative(z):
    return z * (1 - z)

def tanh_function(z):
    return np.tanh(z)

def tanh_deravative(z):
    return (1-np.tanh(z)**2)

def relu_function(z):
    return np.maximum(0,z)

def relu_deravative(z): 
    return 1.0 * (z>0)

def leaky_relu(self, z):
    slope = 0.1
    z = np.maximum(slope * z, z)
    return z
def Error_found(true_values, predicted):
    result = predicted - true_values
#     result = true_values - predicted
    return result

def leaky_relu_deravative(self, z):
    slope = 0.1
    leaky = np.zeros_like(z)
    leaky[z<=0] = slope
    leaky[z>0] = 1
    return leaky

class NeuralNetwork_model:
    def __init__(self, X,y,lr,hiddenlayer, activation_function):
        self.X = X
        self.y = y
        hiddenlayer = 4
        self.lr = 0.001
        x_shape = X.shape[1]
        self.w1 = np.random.randn(x_shape, hiddenlayer)  #(4*350) (350*4)
        self.b1 = np.zeros(hiddenlayer) #(4*1)
        self.w2 = np.random.randn(hiddenlayer, hiddenlayer)
        self.b2 = np.zeros(hiddenlayer)
        self.w3 = np.random.randn(hiddenlayer, 1) #(350*4)
        self.b3 = np.zeros(1)
        self.activation_function = activation_function
        
    def forward_propagation(self, x):
        self.x = x
        if self.activation_function == "sigmoid":
            z1 = np.dot(self.x, self.w1) + self.b1
            self.a1 = sigmoid(z1)
            z2 = np.dot(self.a1, self.w2) + self.b2
            self.a2 = sigmoid(z2)
            z3 = np.dot(self.a2, self.w3) + self.b3
            self.a3 = sigmoid(z3)
            return self.a3
        
        elif self.activation_function == "relu":
            z1 = np.dot(self.x, self.w1) + self.b1
            self.a1 = relu_function(z1)
            z2 = np.dot(self.a1, self.w2) + self.b2
            self.a2 = relu_function(z2)
            z3 = np.dot(self.a2, self.w3) + self.b3
            self.a3 = relu_function(z3)
            return self.a3
        
        elif self.activation_function == "tanh":
            z1 = np.dot(self.x, self.w1) + self.b1
            self.a1 = tanh_function(z1)
            z2 = np.dot(self.a1, self.w2) + self.b2
            self.a2 = tanh_function(z2)
            z3 = np.dot(self.a2, self.w3) + self.b3
            self.a3 = tanh_function(z3)
            return self.a3
        
        elif self.activation_function == "leakyrelu":
            z1 = np.dot(self.x, self.w1) + self.b1
            self.a1 = leaky_relu_deravative(z1)
            z2 = np.dot(self.a1, self.w2) + self.b2
            self.a2 = leaky_relu_deravative(z2)
            z3 = np.dot(self.a2, self.w3) + self.b3
            self.a3 = leaky_relu_deravative(z3)
            return self.a3
        
    def backward_propagation(self):    
        if self.activation_function == "sigmoid":
            dA3 = Error_found(self.y,self.a3) # w3
            dZ2 = np.dot(dA3, self.w3.T)
            dA2 = dZ2 * sigmoid_deravative(self.a2) # w2
            dZ1 = np.dot(dA2, self.w2.T)
            dA1 = dZ1 * sigmoid_deravative(self.a1) # w1
        
        elif self.activation_function == "relu":
            dA3 = Error_found(self.y,self.a3) # w3
            dZ2 = np.dot(dA3, self.w3.T)
            dA2 = dZ2 * relu_deravative(self.a2) # w2
            dZ1 = np.dot(dA2, self.w2.T)
            dA1 = dZ1 * relu_deravative(self.a1) # w1
        
        elif self.activation_function == "tanh":
            dA3 = Error_found(self.y,self.a3) # w3
            dZ2 = np.dot(dA3, self.w3.T)
            dA2 = dZ2 * tanh_deravative(self.a2) # w2
            dZ1 = np.dot(dA2, self.w2.T)
            dA1 = dZ1 * tanh_deravative(self.a1) # w1
            
        elif self.activation_function == "leakyrelu":
            dA3 = Error_found(self.y,self.a3) # w3
            dZ2 = np.dot(dA3, self.w3.T)
            dA2 = dZ2 * tanh_deravative(self.a2) # w2
            dZ1 = np.dot(dA2, self.w2.T)
            dA1 = dZ1 * tanh_deravative(self.a1) # w1
        

        self.w3 -= np.dot(self.a2.T, dA3) * self.lr 
        self.b3 -= np.sum(dA3, axis=0) * self.lr 
        self.w2 -= np.dot(self.a1.T, dA2) * self.lr
        self.b2 -= np.sum(dA2, axis=0) * self.lr
        self.w1 -= np.dot(self.x.T, dA1) * self.lr
        self.b1 -= np.sum(dA1, axis=0) * self.lr
        
    def predicted(self,x_test):
        prediction = self.forward_propagation(x_test)
        return prediction
    
dataset = pd.read_csv("circles500.csv")
X_ext = dataset.drop(columns = ['Class']).values
y_ext = dataset.drop(columns = ['X0', 'X1']).values
x_train_ext, x_test_ext, y_train_ext, y_test_ext = train_test_split(X_ext, y_ext, test_size=0.3, random_state=20)

Circle Data-set

In [27]:

print("Circle Dataset: \n")
activations = ["sigmoid", "relu", "tanh"]
for i in activations:
    model_3 = NeuralNetwork_model(x_train_ext, y_train_ext,lr= 0.001, hiddenlayer=6, activation_function = i)
    iteration = 20000
    for x in range(iteration):
        model_3.forward_propagation(x_train_ext)
        model_3.backward_propagation()

    def prediction_3(x_test_ext):
        pred = model_3.predicted(x_test_ext)
        result =[]
        for i in pred:
            if i >= 0.5:
                result.append(1)
            elif i < 0.5:
                result.append(0)
        result = np.array(result)
        
        return result
    
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test_ext, prediction_3(x_test_ext))
    print("Confusion matrix :\n", cm)

    from sklearn.metrics import accuracy_score
    print("Train set Accuracy using ",i,  " :",accuracy_score(y_train_ext, prediction_3(x_train_ext)))
    print("Test  set Accuracy using : ",i, " :",accuracy_score(y_test_ext, prediction_3(x_test_ext)))
    print("========================================================================================================")

Circle Dataset: 

Confusion matrix :
 [[77  0]
 [ 1 72]]
Train set Accuracy using  sigmoid  : 1.0
Test  set Accuracy using :  sigmoid  : 0.9933333333333333
Confusion matrix :
 [[44 33]
 [ 7 66]]
Train set Accuracy using  relu  : 0.8
Test  set Accuracy using :  relu  : 0.7333333333333333
Confusion matrix :
 [[35 42]
 [ 1 72]]
Train set Accuracy using  tanh  : 0.7742857142857142
Test  set Accuracy using :  tanh  : 0.7133333333333334


### Observation 
- We can observe that, for the Circle dataset, using sigmoid or relu as activation function is a better option. 
- However, tanh ended up predicting low on the dataset. 

Cifar Dataset

In [34]:
#Importing necessary libraries
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

#SOURCE: loading code taken from "code_snippets" provided by Michael.Madden
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

def loadbatch(batchname):
    folder = 'cifar-10-batches-py'
    batch = unpickle(folder+"/"+batchname)
    return batch

def loadlabelnames():
    folder = 'cifar-10-batches-py'
    meta = unpickle(folder+"/"+'batches.meta')
    return meta[b'label_names']

batch1 = loadbatch('data_batch_2')

#Loads the data(features)
data = batch1[b'data']
#Loads the target variables
labels = batch1[b'labels']

#Converting to GreyScale
Features = np.mean(data, axis=1)

df = pd.DataFrame({'X':Features, 'Y': labels})

indexNames = df[ (df['Y'] != 1) & (df['Y'] != 0) ].index #Filtering only bird and auto-mobile class
df.drop(indexNames , inplace=True)

XX = df.drop(['Y'], axis=1).values
YY = df.drop(['X'], axis=1).values

X_train_ext, X_test_ext, Y_train_ext, Y_test_ext = train_test_split(XX, YY, test_size=0.3)

ss = StandardScaler() #normalize the data  

X_train_ext = ss.fit_transform(X_train_ext)
X_test_ext = ss.transform(X_test_ext)

print("Performance on Large CIFAR Dataset: \n")
activations = ["sigmoid", "relu", "tanh"]
for i in activations:
    model_3 = NeuralNetwork_model(X_train_ext, Y_train_ext,lr= 0.001, hiddenlayer=6, activation_function = i)
    iteration = 20000
    for x in range(iteration):
        model_3.forward_propagation(X_train_ext)
        model_3.backward_propagation()

    def prediction_3(X_test_ext):
        pred = model_3.predicted(X_test_ext)
        result =[]
        for i in pred:
            if i >= 0.5:
                result.append(1)
            elif i < 0.5:
                result.append(0)
        result = np.array(result)
        return result
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(Y_test_ext, prediction_3(X_test_ext))
    print("Confusion matrix :\n", cm)

    from sklearn.metrics import accuracy_score
    print("Train set Accuracy for ",i,  " :",accuracy_score(Y_train_ext, prediction_3(X_train_ext)))
    print("Test  set Accuracy: ",i, " :",accuracy_score(Y_test_ext, prediction_3(X_test_ext)))
    print("========================================================================================================")

Performance on Large CIFAR Dataset: 

Confusion matrix :
 [[187  90]
 [ 88 233]]
Train set Accuracy for  sigmoid  : 0.6812634601579325
Test  set Accuracy:  sigmoid  : 0.7023411371237458
Confusion matrix :
 [[200  77]
 [111 210]]
Train set Accuracy for  relu  : 0.6805455850681982
Test  set Accuracy:  relu  : 0.68561872909699
Confusion matrix :
 [[178  99]
 [ 78 243]]
Train set Accuracy for  tanh  : 0.6884422110552764
Test  set Accuracy:  tanh  : 0.7040133779264214


References
- [1] https://towardsdatascience.com/understanding-neural-networks-what-how-and-why-18ec703ebd31
- [2] Andrew Ng- DeepLearning youtube. 